apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lh-test-5g
  namespace: default
  labels: {app: lh-test}
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: longhorn
  resources: {requests: {storage: 5Gi}}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lh-test-10g
  namespace: default
  labels: {app: lh-test}
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: longhorn
  resources: {requests: {storage: 10Gi}}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lh-test-20g
  namespace: default
  labels: {app: lh-test}
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: longhorn
  resources: {requests: {storage: 20Gi}}
